vich_uploader:
    db_driver: orm

    mappings:
       recipes:
           uri_prefix: /images/recipes
           upload_destination: '%kernel.project_dir%/public/images/recipes'
           namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug' }
